### PR TITLE
chore/deps_downloader: configuration to download both mock and prod libs without needing NODE_ENV=dev

### LINKED ISSUE #277: Install dev and prod libs by default
When `yarn`ing, you're a dev. 

Having to remember to add `NODE_ENV=dev` on install is a PITA.

I propose we download both by default and leave it up to the app to exclude the dir they don't want in their build...

### PR DESCRIPTION
**Pull request by hunterlester**
Resolves #277

### CODE REVIEW

**Comment by hunterlester** [comment]
Anyone wondering why this configuration works, it's because `NODE_ENV=development is by [default](https://github.com/maidsafe/deps_downloader/blob/master/cli.js#L30).

**Comment by bochaco** [comment]
@hunterlester , this looks good to me, although after a bit of testing I have a proposal.

With this change you won't need to specify any env var to install the package, and the native libs for both mock and prod will be installed, that's cool. 
Then when running the app it can either use the `forceUseMock` flag in the initialisation options or use `NODE_ENV=test` to load the native lib which uses the mock vault. That's also cool.

But if you install the package with `NODE_ENV=dev`, what you get installed is only the native lib for live network, which means it's kinda not backward compatible. Thus, what if we changed the default in our `deps_downloader` to be `dev` instead of `development` (or both?) so this change is backward compatible for anyone who is still setting the `NODE_ENV=dev`?

**Comment by hunterlester** [comment]
Tests won't run/pass until https://github.com/maidsafe/deps_downloader/pull/12 is merged.

**Comment by bochaco** [comment]
ok, @hunterlester , we have the new deps_downloader publisbed at https://s3.eu-west-2.amazonaws.com/deps-downloader/deps_downloader-0.3.0.tgz

**Pull request merged**
